### ISSUE TITLE
Softhyphen has contours

### ISSUE THREAD

**Issue by guidoferreyra** [canonical/Ubuntu-fonts#60]
⚠️ WARN

This font has a 'Soft Hyphen' character (codepoint 0x00AD) which is supposed to be zero-width and invisible, and is used to mark a hyphenation possibility within a word in the absence of or overriding dictionary hyphenation. It is mostly an obsolete mechanism now, and the character is only included in fonts for legacy codepage coverage. [code: softhyphen]

**Comment by djrrb** [comment]
@glenda-tn what is your recommendation on the width of softhyphen in a monospace?

**Comment by glenda-tn** [comment]
hmm. That's a good question. Is zero-width not allowed in a monospace? If not, I wonder if a GPOS entry could collapse it to 0. @guidoferreyra do you know anything about this? I could ask Christopher Chapman who wrote the entry for Unicode 15.

**Comment by djrrb** [comment]
https://typedrawers.com/discussion/comment/12702/#Comment_12702 😵

**Comment by glenda-tn** [comment]
yes, that's why I suggested about the GPOS trick. Try setting the sfthyphen to 0 first and let's run it through FB. I imagine it should be ok because that's Google FB check. 

I also think that we will want the isFixedPitch flag checked so that the font shows up in the FixedPitch Font menus. Other fonts that are monospaced, but don't meet all of the requirements (like they have dbl wide) are marketed as monospaced but as mentioned in the thread, don't have the isFixedPitch flag set or even the Panose flag set. It is important to NOT set these flags if there are double wide glyphs---because MS Office will otherwise force the fixed width.

**Comment by djrrb** [comment]
So, at least in Glyphsapp, if Fixed Pitch is set, it won’t allow you to set these at any other width than the monospace width. So rather than do something hacky in post-production, my feeling is that we can leave it at the monospace width.

**Comment by glenda-tn** [comment]
Given our findings with Roboto—it seems the Shapers will collapse uni00AD to 0 anyway. So yes, leave it at monowidth but do not put an outline in it.

**Comment by djrrb** [comment]
Removing contours.

**Comment by djrrb** [comment]
Pushed in e16eed91024b8f645f306c2ac6e17ee5307ea784
