### ISSUE TITLE
unreachables

### ISSUE THREAD

**Issue by glenda-tn** [canonical/Ubuntu-fonts#74]
In various styles the following are reported as unreachable:

- [ ] uni030C.alt
- [x] fi
- [x] fl 
- [x] revcommaaccent

Currently f_i and f_l are encoded to FB01 and FB02, respectively. It should be the reverse: fi and fl should be encoded. Alternatively, remove the duplicate and keep the fi and fl names. From [GlyphsApp](https://glyphsapp.com/learn/ligatures):

> You may have noticed that fi and fl do not adhere to the naming convention we mentioned above. That’s because they are historical exceptions. These two glyph names were there long before OpenType. Actually, you can still call them f_i and f_l if you want, but again, they’ll go into dlig unless you add the .liga suffix.

I assume the others are components and should be fine. If unused, they can be set to not export.

**Comment by djrrb** [comment]
These components are used. 

Just making sure it’s cool to have the `liga` feature subbing in the encoded `fi` and `fl` glyphs if I remove the underscored ones?

**Comment by guidoferreyra** [comment]
> Just making sure it’s cool to have the `liga` feature subbing in the encoded `fi` and `fl` glyphs if I remove the underscored ones?

`liga`feature uses /f_i and /f_l and I kept the encoded ligatures (/fi and /fl) for legacy support.

I don’t se a problem of keeping vertical caron (uni030C.alt) unreacheable since is used as a component. 

The only other unreacheables are the fractions that are not inclujded by Unicode. To me those glyphs could be deleted since the contextual `fracp feature already cover the cases

- eight_fraction_nine
- five_fraction_nine
- five_fraction_seven
- four_fraction_nine
- four_fraction_seven
- seven_fraction_nine
- six_fraction_seven
- three_fraction_seven
- two_fraction_nine
- two_fraction_seven
