### ISSUE TITLE
Some characters do not react to small caps

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/Ubuntu-fonts#81]
I noticed some of the characters do not have small caps variants, screenshot below:
![image](https://user-images.githubusercontent.com/2741678/225690303-27f7c889-0aa5-4d86-859f-abe8cf4dac39.png)

@djrrb shouldn't these also have small caps alternatives? Or will that be part of the text figures work?
We have an issue filed for the ampersand character for example, I'm wondering what's the best way to get a comprehensive list of those and resolve them, rather than relying on people noticing them.

**Comment by djrrb** [comment]
Hi Lyubo,

Thanks for checking out the small caps! 

Yes, we will be drawing currency and basic math variants to match the old-style figures. 

AFAIK there is no standard list of which non-alphabetic characters get small cap variants. I tend to prefer a lighter touch here, to avoid overloading the font with lots of slightly-different variants, and only implementing them when [All-Small-Caps](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-caps) is activated (so that when uppercase is mixed in, the default punctuation is used.)

I find that when characters like the quotation marks, brackets, slashes, the `@` sign, asterisk, etc. rise a bit above the small caps it helps make them feel like proper small caps rather than caps at a different font size. So I would suggest we use their default forms, unless you think small cap variants are necessary.

I could imagine a small set of punctuation getting implemented for all-small-caps, something like `&¡!¿? -–—•«»‹›`...if that sounds good to you?

**Comment by djrrb** [comment]
@genramirez and @zrinzrin are currently wrapping up the small caps, and just wanted to double check to see if you ended up wanting to go with additional small-cap punctuation beyond `&¡!¿? -–—•«»‹›`?

**Comment by lyubomir-popov** [comment]
Hi @djrrb given our use case (the all small caps is  one of our headings styles), the wider the set the better. I've looked at a few examples, I like Filosofia Reg All Small Caps (https://fonts.adobe.com/fonts/filosofia):

![image](https://user-images.githubusercontent.com/2741678/232719431-2685058d-5c51-4767-9914-512180f817fc.png)

Can we have a similar set?

**Comment by lyubomir-popov** [comment]
Hi I just noticed that cyrillic characters als odo not respond to small caps.

**Comment by djrrb** [comment]
I think this is now resolved!

**Comment by fitojb** [comment]
Thanks for adding a small-cap for Eszett @djrrb! Nice detail!
![imatge](https://github.com/canonical/Ubuntu-fonts/assets/554953/baed076b-76cd-478f-9331-74bdbbf5cda7)
